local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 10.0 #6.0
  height: 10.0 #6.0
  resolution: 0.01
  transform_tolerance: 0.5
  map_type: costmap